"""add_embedding_column_to_intelligence_assets

Revision ID: ba512767ec0a
Revises: bfb9d16db0ef
Create Date: 2026-07-27 08:32:29.419194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba512767ec0a'
down_revision: Union[str, Sequence[str], None] = 'bfb9d16db0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intelligence_assets', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the asset',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Human-readable name of the asset',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description of the asset',
               existing_nullable=True)
    op.alter_column('intelligence_assets', 'owner_department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Responsible department (e.g., Water Resources)',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'domain',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='One of the 18 Sahyadri domains (e.g., water, agriculture)',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Automated quality score (0-100)',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Has this asset been verified by a human/domain expert?',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'source_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original provenance/URL of the data',
               existing_nullable=True)
    op.alter_column('intelligence_assets', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Semantic version of the asset',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intelligence_assets', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='Semantic version of the asset',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'source_url',
               existing_type=sa.TEXT(),
               comment='Original provenance/URL of the data',
               existing_nullable=True)
    op.alter_column('intelligence_assets', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Has this asset been verified by a human/domain expert?',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Automated quality score (0-100)',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'domain',
               existing_type=sa.VARCHAR(length=50),
               comment='One of the 18 Sahyadri domains (e.g., water, agriculture)',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'owner_department',
               existing_type=sa.VARCHAR(length=100),
               comment='Responsible department (e.g., Water Resources)',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed description of the asset',
               existing_nullable=True)
    op.alter_column('intelligence_assets', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Human-readable name of the asset',
               existing_nullable=False)
    op.alter_column('intelligence_assets', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the asset',
               existing_nullable=False)
    # ### end Alembic commands ###
