"""create intelligence_assets table

Revision ID: edf605838fea
Revises: 
Create Date: 2026-07-19 09:12:13.769614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf605838fea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_assets',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the asset'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name of the asset'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the asset'),
    sa.Column('owner_department', sa.String(length=100), nullable=False, comment='Responsible department (e.g., Water Resources)'),
    sa.Column('domain', sa.String(length=50), nullable=False, comment='One of the 18 Sahyadri domains (e.g., water, agriculture)'),
    sa.Column('quality_score', sa.Float(), nullable=False, comment='Automated quality score (0-100)'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Has this asset been verified by a human/domain expert?'),
    sa.Column('source_url', sa.Text(), nullable=True, comment='Original provenance/URL of the data'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Semantic version of the asset'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_assets_domain'), 'intelligence_assets', ['domain'], unique=False)
    op.create_index(op.f('ix_intelligence_assets_name'), 'intelligence_assets', ['name'], unique=False)
    op.create_index(op.f('ix_intelligence_assets_owner_department'), 'intelligence_assets', ['owner_department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_assets_owner_department'), table_name='intelligence_assets')
    op.drop_index(op.f('ix_intelligence_assets_name'), table_name='intelligence_assets')
    op.drop_index(op.f('ix_intelligence_assets_domain'), table_name='intelligence_assets')
    op.drop_table('intelligence_assets')
    # ### end Alembic commands ###
