run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username: sahyadri
      password: sahyadri_secret
      hostname: postgres
      port: 5432
      db_name: sahyadri_db

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username: sahyadri
      password: sahyadri_secret
      hostname: postgres
      port: 5432
      db_name: sahyadri_db

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username: sahyadri
      password: sahyadri_secret
      hostname: postgres
      port: 5432
      db_name: sahyadri_db
