"""
Sprint 41.5: Operational Maturity Matrix Harness.
"""

import asyncio
import sys
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.core.connectors.factory import load_connector_configs
from src.core.connectors.protocols.rest import RESTConnector
from src.core.connectors.protocols.stac import STACConnector
from src.core.connectors.protocols.download import DownloadConnector


def categorize_failure(error_msg: str, cfg: Any) -> tuple[str, str]:
    if getattr(cfg, "auth_required", False):
        return "Auth Required", getattr(cfg, "blocked_reason", "Needs API Key")
    if cfg.type in ["manual", "scraper"]:
        return "Not Probed", f"{cfg.type.capitalize()} source (No REST/STAC probe)"

    err = error_msg.lower()
    if "400 bad request" in err or "422" in err:
        return "Request Fix", "Malformed payload"
    if "404 not found" in err:
        return "Endpoint Fix", "Stale URL"
    if "403 forbidden" in err or "401" in err:
        return "Auth Required", "WAF block / Missing Creds"
    if "500 internal server error" in err:
        return "Upstream Error", "Server-side failure"
    if "ssl" in err or "tls" in err:
        return "Infra Blocked", "SSL/TLS handshake failure"
    if "name or service not known" in err or "errno -2" in err or "errno -5" in err:
        return "Infra Blocked", "DNS / Internal NIC network"
    if getattr(cfg, "status", "") == "ready":
        return "Auth Required", getattr(cfg, "blocked_reason", "Awaiting Creds")
    if getattr(cfg, "status", "") == "blocked":
        return "Blocked", getattr(cfg, "blocked_reason", "Restricted")
    return "Unknown", error_msg[:50]


async def test_live_connection(cfg: Any) -> Dict[str, Any]:
    result = {
        "name": cfg.name,
        "type": cfg.type.upper(),
        "http": "❌",
        "schema": "—",
        "load": "—",
        "status": "Pending",
        "reason": "Not Tested",
    }

    if (
        cfg.type in ["manual", "scraper"]
        or getattr(cfg, "auth_required", False)
        or cfg.status in ["blocked", "ready"]
    ):
        result["status"], result["reason"] = categorize_failure("", cfg)
        return result

    connector: Any = None
    # Pass ssl_verify to the connector
    ssl_verify = getattr(cfg, "ssl_verify", True)

    if cfg.type == "rest":
        connector = RESTConnector(
            name=cfg.name, base_url=cfg.url, timeout=15.0, max_retries=1
        )
        connector.ssl_verify = ssl_verify
    elif cfg.type == "stac":
        connector = STACConnector(
            name=cfg.name, catalog_url=cfg.catalog_url, timeout=15.0, max_retries=1
        )
        connector.ssl_verify = ssl_verify
    elif cfg.type == "download":
        connector = DownloadConnector(
            name=cfg.name, url=cfg.url, timeout=15.0, max_retries=1
        )
        connector.ssl_verify = ssl_verify

    try:
        if cfg.type == "rest":
            res = await connector.fetch_paginated(
                endpoint="", params=getattr(cfg, "params", {}), max_pages=1
            )
        elif cfg.type == "stac":
            res = await connector.search_items(
                collections=getattr(cfg, "collections", []),
                bbox=getattr(cfg, "bbox", None) or [72.5, 15.5, 81.0, 22.5],
                datetime_range=getattr(cfg, "datetime_range", None)
                or "2023-01-01/2023-01-02",
                limit=5,
            )
        else:
            res = await connector.fetch()

        if res.success:
            result.update(
                {
                    "http": "✅",
                    "schema": "✅",
                    "load": "✅",
                    "status": "Production",
                    "reason": "—",
                }
            )
        else:
            result["status"], result["reason"] = categorize_failure(
                res.error_message, cfg
            )
    except Exception as e:
        result["status"], result["reason"] = categorize_failure(str(e), cfg)

    return result


async def run_harness():
    print("\n" + "=" * 80)
    print("🛡️  SAHYADRI OPERATIONAL MATURITY MATRIX (SPRINT 41.5)")
    print("=" * 80)

    configs = load_connector_configs("configs/connectors")
    sem = asyncio.Semaphore(5)

    async def bounded_test(cfg):
        async with sem:
            return await test_live_connection(cfg)

    results = await asyncio.gather(*[bounded_test(cfg) for cfg in configs])

    report_path = Path("docs/CATALOG_MATURITY_REPORT.md")
    with open(report_path, "w") as f:
        f.write("# 📊 Sahyadri Master Data Catalog: Operational Maturity Matrix\n\n")
        f.write(
            "*Auto-generated by Sprint 41.5 Harness. Grouped by Ingestion Method.*\n\n"
        )
        f.write("| Source | Type | HTTP | Schema | Load | Status | Reason |\n")
        f.write("|---|---|---|---|---|---|---|\n")

        counts = {
            "Production": 0,
            "Auth Required": 0,
            "Not Probed": 0,
            "Request Fix": 0,
            "Infra Blocked": 0,
            "Other": 0,
        }

        for r in sorted(results, key=lambda x: (x["type"], x["name"])):
            f.write(
                f"| **{r['name']}** | {r['type']} | {r['http']} | {r['schema']} | {r['load']} | **{r['status']}** | {r['reason']} |\n"
            )
            if r["status"] in counts:
                counts[r["status"]] += 1
            else:
                counts["Other"] += 1

        f.write("\n---\n### Summary\n")
        for k, v in counts.items():
            f.write(f"- **{k}:** {v}\n")

    print(f"✅ Matrix generated at: {report_path}")
    print(f"🏆 {counts['Production']} sources in Production.")
    print("=" * 80 + "\n")


if __name__ == "__main__":
    asyncio.run(run_harness())
